apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-demo            # Pod name
  namespace: default              # Namespace where the Pod will run

spec:
  containers:
  # ---------------------------------------------------------------
  # 1 FIRST CONTAINER — NGINX
  # ---------------------------------------------------------------
  - name: nginx                   # Container name
    image: nginx                  # Runs NGINX server

    # Mount the emptyDir volume at /var/log/nginx
    # NGINX will write its access logs + error logs here.
    volumeMounts:
    - mountPath: /var/log/nginx   # Log directory inside NGINX container
      name: nginx-logs            # Volume name to mount

  # ---------------------------------------------------------------
  # 2 SECOND CONTAINER — ALMALINUX (SIDE-CAR)
  # ---------------------------------------------------------------
  - name: almalinux               # Sidecar container
    image: almalinux:9
    command: ["sleep", "1000"]    # Keeps the container running for testing

    # Mount the same emptyDir volume in read-only mode.
    # This container can *read* logs written by the NGINX container.
    volumeMounts:
    - mountPath: /mnt/nginx-log   # Mount path inside Almalinux container
      name: nginx-logs
      readOnly: true              # Sidecar cannot modify logs, only read

  # ---------------------------------------------------------------
  # 3 VOLUME DEFINITION — emptyDir
  # ---------------------------------------------------------------
  volumes:
  - name: nginx-logs              # Same volume shared by both containers

    emptyDir:
      sizeLimit: 100Mi            # Max allowed size for this temp volume
      # emptyDir NOTES:
      # - Created when Pod starts
      # - Deleted when Pod is deleted
      # - Data survives container restart
      # - Data does NOT survive Pod rescheduling
