# =====================================================================
# 1) PERSISTENT VOLUME CLAIM (Dynamic EFS Provisioning)
# =====================================================================
# - When this PVC is created, Kubernetes will:
#     ✔ Call the StorageClass "roboshop-efs"
#     ✔ EFS CSI driver will dynamically create:
#           → An EFS Access Point
#           → A dedicated directory inside the EFS filesystem
#           → A PersistentVolume (PV)
#
# - EFS supports ReadWriteMany (RWX) which allows:
#     → Multiple Pods across multiple nodes to share the same storage
# =====================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic                     # PVC name
spec:
  accessModes:
    - ReadWriteMany                    # RWX = many Pods can access simultaneously (EFS feature!)

  storageClassName: roboshop-efs        # Uses the dynamic EFS StorageClass (efs-ap mode)

  resources:
    requests:
      storage: 5Gi                      # Logical size; EFS is elastic so it grows automatically


---
# =====================================================================
# 2) POD USING THE DYNAMIC EFS PVC
# =====================================================================
# - When the Pod starts:
#     ✔ The PVC binds to the dynamically created PV
#     ✔ The EFS Access Point created for this PVC is mounted into the Pod
#
# - No nodeSelector required:
#     → EFS works across ALL nodes and ALL AZs in the region.
#     → Unlike EBS, EFS is NOT AZ-bound.
#
# - Data stored at /usr/share/nginx/html will persist across:
#     ✔ Pod restarts
#     ✔ Node failures
#     ✔ Rescheduling
#     ✔ Cluster upgrades (as long as EFS exists)
#
# - Multiple Pods can mount the same PVC (shared content)
# =====================================================================
apiVersion: v1
kind: Pod
metadata:
  name: nginx                          # Pod name
  labels:
    purpose: efs-dynamic               # Used for Services if needed
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html # EFS directory mounted here for Nginx content

  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-dynamic           # Bind PVC to the Pod