apiVersion: v1
kind: Service                           # We are creating a Service object
metadata:
  name: nginx-lb                         # Name of the Service
  namespace: roboshop                    # Namespace where the Service will be created
spec:
  type: LoadBalancer                     # Exposes the Service to the Internet using a Cloud Load Balancer
  selector:                              # Selects Pods that match these labels
    project: roboshop                    # Pod must have this label
    component: frontend                  # Pod must have this label
    environment: dev                     # Pod must have this label
    purpose: load-balancer               # Pod must have this label
  ports:
    - protocol: TCP                      # Protocol used (TCP is default for web apps)
      port: 80                           # Service port (LB listens on this port)
      targetPort: 80                     # Container port inside the Pod
      nodePort: 30007                    # Optional for LoadBalancer; NodePort used internally